services:
  api:
    build: .
    container_name: dean_office_api
    ports:
      - "3010:3010"
    volumes:
      - .:/app_code
      - ./data:/app_code/data
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///./data/dekanat.db
      - JWT_SECRET_KEY=my-dev-secret-key-32-chars-long!!
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
<<<<<<< HEAD
    restart: unless-stopped
=======
    restart: unless-stopped
>>>>>>> d973f17719bd5942e8860d475ef240ce8b54d319
