"""add audit_log table

Revision ID: a704f08c7ca7
Revises: 0a2d61a7cd6f
Create Date: 2026-05-25 11:54:12.329147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a704f08c7ca7'
down_revision: Union[str, Sequence[str], None] = '0a2d61a7cd6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('encrypted_phone', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.drop_column('users', 'encrypted_phone')
    op.drop_column('users', 'encrypted_email')
    # ### end Alembic commands ###
